### ISSUE TITLE
playlist_output on final page missing nesting

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Quickstart#132]
playlist_files output on final page looks like this:
`playlist_files:
  template_variables: Movies, Test Videos, TestTV Shows, TV Shows`
  
instead of 
`playlist_files:
- default: playlist
  template_variables:
    libraries: Movies, Test Videos, TestTV Shows, TV Shows`

Good:
![image](https://github.com/user-attachments/assets/12f7ea11-1bc8-4c86-8d67-2a62d7790edf)

Bad:
![image](https://github.com/user-attachments/assets/45fd8edf-d550-485b-90e1-d18ad17a6ce5)

**Comment by bullmoose20** [comment]
Need to also address null value being written out.

As per Yozora:

Only thing I noticed "template_variables" hiding in Playlist, I can't scroll to it and it does end up in the final YAML with `null` value, plus `- default: playlist` is missing the `-`:

```
playlist_files:
  default: playlist
  libraries: Movies, TV Shows
  template_variables: null
```
