### ISSUE TITLE
Entering minimal TMDB data produces bad config

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Quickstart#184]
I entered only the key, left all the rest alone.  Config contains:
```yaml
##############################
#  _____ __  __ ____  _      #
# |_   _|  \/  |  _ \| |__   #
#   | | | |\/| | | | | '_ \  #
#   | | | |  | | |_| | |_) | #
#   |_| |_|  |_|____/|_.__/  #
#                            #
##############################
tmdb:
  apikey: a1ecc4756c86c26f4bfedc209127a6b0
  cache_expiration: 60
  language: en
  region:
```
Which fails validation with:
```
None is not of type 'string'

Failed validating 'type' in schema['properties']['tmdb']['properties']['region']:
    {'description': 'This field can be either null or a valid ISO 3166-1 '
                    'Code.',
     'enum': ['',
              'AD',
              'AE',
... Redacted for space ...
              'ZR',
              'ZW'],
     'type': 'string'}

On instance['tmdb']['region']:
    None
```
