### ISSUE TITLE
Radarr/Sonarr screens do not validate that all required inputs are present

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Quickstart#190]
I didn't fill in anything but the URL and API key; QS let me continue then failed the config because of the missing fields.

```
radarr:
  add_existing: false
  add_missing: false
  availability: announced
  ignore_cache: false
  monitor: true
  monitor_existing: false
  plex_path:
  radarr_path:
  search: false
  tag:
  token: BLAH
  upgrade_existing: false
  url: http://192.168.1.11:7878

sonarr:
  add_existing: false
  add_missing: false
  cutoff_search: false
  ignore_cache: false
  monitor: all
  monitor_existing: false
  plex_path:
  search: false
  season_folder: true
  series_type: standard
  sonarr_path:
  tag:
  token: BLAH
  upgrade_existing: false
  url: http://192.168.1.11:8989
```
`root_path` and `quality_profile` are missing, at least
