### ISSUE TITLE
[Suggestion] Move library-level template variables

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Quickstart#266]
In my opining, the positioning of the library-level template variables is hard to understand.

In this example, it looks like template_variables is part of the `mediastinger` Defaults File.
```
libraries:
  Movies:
    collection_files:
    - default: separator_award
    - default: separator_chart
    - default: tmdb
    overlay_files:
    - default: mediastinger
    template_variables:         # here
      use_separators: true
      sep_style: plum

```
I think this would make more sense as:
```
libraries:
  Movies:
    template_variables:         # here
      use_separators: true
      sep_style: plum
    collection_files:
    - default: separator_award
    - default: separator_chart
    - default: tmdb
    overlay_files:
    - default: mediastinger
```

**Comment by bullmoose20** [comment]
Try to build a full kitchen sink config to see if you see other spots where the output order could be better.

Iirc, reset overlays and remove overlays was supposed to be just above the overlay_files section. Without one, what does it look like. With one how does it look like.

The library level template variables one in this suggestion is valid.

**Comment by YozoraXCII** [comment]
Here is a kitchen sink:

```
libraries:
  Movie Recommendations:
    collection_files:
    - default: separator_award
    - default: oscars
    - default: berlinale
    - default: bafta
    - default: cannes
    - default: cesar
    - default: choice
    - default: emmy
    - default: golden
    - default: spirit
    - default: nfr
    - default: pca
    - default: razzie
    - default: sag
    - default: sundance
    - default: tiff
    - default: venice
    - default: separator_chart
    - default: basic
    - default: tautulli
    - default: imdb
    - default: tmdb
    - default: trakt
    - default: anilist
    - default: myanimelist
    - default: letterboxd
    - default: other_chart
    - default: genre
    - default: franchise
    - default: universe
    - default: based
    - default: collectionless
    - default: content_rating_us
    - default: content_rating_uk
    - default: content_rating_de
    - default: content_rating_au
    - default: content_rating_nz
    - default: content_rating_mal
    - default: content_rating_cs
    - default: country
    - default: region
    - default: continent
    - default: aspect
    - default: resolution
    - default: audio_language
    - default: subtitle_language
    - default: streaming
    - default: studio
    - default: actor
    - default: director
    - default: producer
    - default: writer
    - default: seasonal
    - default: year
    - default: decade
    overlay_files:
    - default: ribbon
    - default: mediastinger
    - default: content_rating_us_movie
    - default: content_rating_uk
    - default: content_rating_de
    - default: content_rating_au
    - default: content_rating_nz
    - default: commonsense
    - default: aspect
    - default: audio_codec
    - default: language_count
    - default: languages
    - default: resolution
    - default: runtimes
    - default: versions
    - default: video_format
    - default: streaming
    - default: studio
    - default: direct_play
    template_variables:                   # THIS COULD BE JUST BELOW THE LIBRARY NAME
      use_separators: true
      sep_style: amethyst
    remove_overlays: true              # THIS COULD BE ABOVE OVERLAY_FILES
    reset_overlays: plex                  # THIS COULD BE ABOVE OVERLAY_FILES
```
