### ISSUE TITLE
[Suggestion] Add `placeholder_*` entries for Separators

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Quickstart#396]
Separators can be buggy without any items, so I suggest that below the style selector, we have a dropdown for "Placeholder TMDb Movie ID / Placeholder IMDb ID" for Movies and "Placeholder TVDB Show ID / Placeholder IMDb ID" for Shows, which adds the ID as a template variable:
```yaml
libraries:
  Movies:
    template_variables:
      placeholder_imdb_movie: tt0076759
  TV Shows:
    template_variables:
      placeholder_imdb_movie: tt0076759
```
