### ISSUE TITLE
[Feature]: add language template_variable

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Quickstart#612]
### Describe the Feature Request

```
   template_variables:
      sep_style: gray                               # use the gray separators globally for this library
      collection_mode: hide                         # hide the collections
      language: en                                  # could be default(which is en), da, de, fr, pt-br or another lang code that we have translated
      placeholder_imdb_id: tt8579674                # 1917 (2019) placeholder id for the separators
```
