### ISSUE TITLE
Add use_<<key>> template_variables to collections

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Quickstart#638]
One drawback I guess would be that for `default: chart` instead of one line, you'd end up with an additional four lines:

```yml
libraries:
  4K Movies: 
    collection_files:
      - default: chart
        template_variables:
          use_lowest: true 
          use_popular: true 
          use_top: true 
```
