### ISSUE TITLE
Various settings values end up as '0' instead of boolean

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Quickstart#76]
```
settings:
  asset_directory:
  asset_folders: 0
  create_asset_folders: 0
  asset_depth:
  prioritize_assets: 0
  dimensional_asset_rename: 0
  download_url_assets: 0
  show_missing_assets: 0
  show_missing_season_assets: 0
  show_missing_episode_assets: 0
  show_asset_not_needed: 0
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
  cache: 0
  cache_expiration:
  sync_mode: append
  default_collection_order:
  item_refresh_delay:
  minimum_items:
  show_missing: 0
  delete_below_minimum: 0
  delete_not_scheduled: 0
  run_again_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: 0
  missing_only_released: 0
  show_unconfigured: 0
  show_unmanaged: 0
  show_filtered: 0
  only_filter_missing: 0
  save_report: 0
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  show_options: 0
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  verify_ssl: 0
  custom_repo:
```
